Repository robot-lab/tinkoff-web-service, pull requests merged in 2018-08, with the labels that each got.

#20 Remove one button processing from prediction page.
  predictor/views.py
  templates/predictor/index.html
Labels: invalid

#22 Page prediction
  predictor/urls.py
  static/img/logo.png
  templates/predictor/index.html
  tinkoff_web_service/settings.py
  tinkoff_web_service/urls.py
Labels: enhancement, invalid, technical debt

#27 Page authorization
  predictor/urls.py
  predictor/views.py
  static/img/logo1.png
  templates/predictor/auth.html
  templates/predictor/index.html
Labels: bug, enhancement, technical debt

#28 Add ml algorithm
  ml_algorithm/__init__.py
  ml_algorithm/log_config.json
  ml_algorithm/logger.py
  ml_algorithm/ml_config.json
  ml_algorithm/models/__init__.py
  ml_algorithm/models/k_nearest_neighbors.py
  ml_algorithm/models/linear_model.py
  ml_algorithm/models/model.py
  ml_algorithm/models/random_forest.py
  ml_algorithm/parsers/__init__.py
  ml_algorithm/parsers/linear_model_parser.py
  ml_algorithm/parsers/parser.py
  ml_algorithm/shell.py
  ml_algorithm/tester.py
  predictor/views.py
  predictor/views_utils.py
  requirements.txt
  tinkoff_web_service/settings.py
Labels: develop process, enhancement, technical debt

#29 Added registration page with stubs for backend.
  predictor/urls.py
  predictor/views.py
  templates/predictor/auth.html
  templates/predictor/register.html
Labels: enhancement, technical debt

#32 Fixed screens "Authorization" and "Prediction"
  predictor/views.py
  templates/predictor/auth.html
  templates/predictor/index.html
Labels: bug

#33 Added "Research" page and all links are clickable
  predictor/urls.py
  predictor/views.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/research.html
Labels: enhancement

#37 Add user auth
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
  predictor/admin.py
  predictor/migrations/__init__.py
  predictor/models.py
  predictor/views.py
  predictor/views_utils.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/research.html
  tinkoff_web_service/settings.py
Labels: develop process, enhancement, technical debt

#38 Email validation function renamed.
  predictor/views.py
  predictor/views_utils.py
Labels: invalid

#41 Machine learning algorithm updated.
  ml_algorithm/__init__.py
  ml_algorithm/logger.py
  ml_algorithm/ml_config.json
  ml_algorithm/models/k_nearest_neighbors.py
  ml_algorithm/models/linear_model.py
  ml_algorithm/models/random_forest.py
  ml_algorithm/parsers/config_parsers.py
  ml_algorithm/parsers/linear_model_parser.py
  ml_algorithm/parsers/parser.py
  ml_algorithm/shell.py
  ml_algorithm/tester.py
  predictor/views_utils.py
Labels: enhancement

#42 Fix "Logout" button
  templates/predictor/index.html
  templates/predictor/research.html
Labels: bug, technical debt

#43 Auto update ml algorithm
  ml_algorithm/models/__init__.py
  ml_algorithm/parsers/__init__.py
  mlalgorithms/__init__.py
  mlalgorithms/log_config.json
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/__init__.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/__init__.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/linear_model_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/views_utils.py
Labels: enhancement

#39 First stable version
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  LICENSE
  README.md
  mlalgorithms/__init__.py
  mlalgorithms/log_config.json
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/__init__.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/__init__.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/linear_model_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/__init__.py
  predictor/admin.py
  predictor/apps.py
  predictor/models.py
  predictor/tests.py
  predictor/urls.py
  predictor/views.py
  predictor/views_utils.py
  requirements.txt
  static/img/logo.png
  static/img/logo1.png
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/research.html
  templates/predictor/restore.html
  tinkoff_web_service/settings.py
  tinkoff_web_service/urls.py
Labels: develop process, enhancement, technical debt

#45 Add user separation.
  predictor/views.py
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/research.html
Labels: enhancement

#47 Changed fields names
  templates/predictor/auth.html
  templates/predictor/register.html
  templates/predictor/restore.html
Labels: bug

#48 Updated result presentation
  mlalgorithms/__init__.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/views.py
  predictor/views_utils.py
Labels: enhancement

#51 Add settings for users
  mlalgorithms/__init__.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/admin.py
  predictor/models.py
  predictor/views.py
  predictor/views_utils.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/research.html
  templates/predictor/restore.html
Labels: enhancement

#58 Add pre settings
  .github/pull_request_template.md
  README.md
  mlalgorithms/parsers/common_parser.py
  predictor/admin.py
  predictor/models.py
  predictor/views.py
  settings_installation.py
  templates/predictor/index.html
Labels: develop process

#62 Added new fields on the page "Register"
  templates/predictor/register.html
  templates/predictor/research.html
Labels: enhancement, invalid

#63 Add settings for users
  README.md
  mlalgorithms/log_config.json
  predictor/views.py
  tinkoff_web_service/settings.py
Labels: develop process, enhancement

#66 Added field with adding file with "Menu"
  templates/predictor/index.html
Labels: enhancement

#67 Added comments for views and models.
  predictor/models.py
  predictor/views.py
  predictor/views_utils.py
  settings_installation.py
Labels: develop process

#68 Change registrstion page
  predictor/models.py
  predictor/views.py
Labels: enhancement

#69 Added fields to "Research" page
  templates/predictor/research.html
Labels: enhancement

#75 Page restore
  predictor/views.py
  templates/predictor/restore.html
Labels: enhancement

#77 Fixed error messages.
  predictor/views.py
  predictor/views_utils.py
Labels: bug

#79 Add researcher page
  mlalgorithms/ml_config.json
  predictor/models.py
  predictor/views.py
  predictor/views_utils.py
  settings_installation.py
Labels: bug, enhancement

#81 Add researcher page
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/models.py
  predictor/views.py
  predictor/views_utils.py
  requirements.txt
  settings_installation.py
  templates/predictor/research.html
Labels: enhancement

#86 Fix static in production version.
  predictor/views.py
  predictor/views_utils.py
  static_delivery/__init__.py
  static_delivery/admin.py
  static_delivery/apps.py
  static_delivery/models.py
  static_delivery/tests.py
  static_delivery/urls.py
  static_delivery/views.py
  tinkoff_web_service/settings.py
  tinkoff_web_service/urls.py
Labels: bug

#83 Alarm messages
  predictor/views.py
  predictor/views_utils.py
  settings_installation.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/restore.html
Labels: enhancement, frontend

#88 Fixed old bugs
  predictor/views.py
  templates/predictor/register.html
  tinkoff_web_service/settings.py
Labels: bug

#92 Save data on registration page
  templates/predictor/register.html
Labels: enhancement, frontend

#94 Fix research page
  templates/predictor/research.html
  tinkoff_web_service/settings.py
Labels: enhancement, frontend

#97 Add testst and refactor
  predictor/tests.py
  predictor/tests/__init__.py
  predictor/tests/test_auth.py
  predictor/tests/test_register.py
  predictor/tests/test_restore.py
  predictor/views.py
  predictor/views_utils.py
  settings_installation.py
  tinkoff_web_service/settings.py
Labels: backend, bug, enhancement

#98 Third stable
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/models.py
  predictor/tests/__init__.py
  predictor/tests/test_auth.py
  predictor/tests/test_register.py
  predictor/tests/test_restore.py
  predictor/views.py
  predictor/views_utils.py
  requirements.txt
  settings_installation.py
  static_delivery/__init__.py
  static_delivery/admin.py
  static_delivery/apps.py
  static_delivery/models.py
  static_delivery/tests.py
  static_delivery/urls.py
  static_delivery/views.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/register.html
  templates/predictor/research.html
  templates/predictor/restore.html
  tinkoff_web_service/settings.py
  tinkoff_web_service/urls.py
Labels: backend, bug, develop process, enhancement, frontend

#100 Update ml_algorithm.
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/linear_model_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  requirements.txt
Labels: enhancement

#101 Add any user access to server.
  tinkoff_web_service/settings.py
Labels: bug

#112 Fix auth page
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/linear_model_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  requirements.txt
  templates/predictor/auth.html
  tinkoff_web_service/settings.py
Labels: bug, frontend

#113 Fix bug with long file names
  templates/predictor/index.html
  templates/predictor/research.html
Labels: bug, frontend

#116 Fix labels and error message
  templates/predictor/index.html
Labels: bug, frontend

#119 Update ml_algorithm
  mlalgorithms/checks.py
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
Labels: enhancement

#118 Fourth stable
  mlalgorithms/checks.py
  mlalgorithms/log_config.json
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  predictor/models.py
  predictor/tests/test_auth.py
  predictor/tests/test_index.py
  predictor/tests/test_register.py
  predictor/tests/test_research.py
  predictor/tests/test_restore.py
  predictor/views.py
  predictor/views_utils.py
  templates/predictor/auth.html
  templates/predictor/index.html
  templates/predictor/research.html
Labels: backend, bug, develop process, enhancement, frontend, research, technical debt

#123 Update ml_algorithm
  mlalgorithms/models/model.py
Labels: bug, enhancement
